///
/// 内置备用词表与常见同音词：只在词库凑不出混淆项时兜底，平时用不到。
///
/// 为什么要有备用词表：刚开始用 App 时词库里可能只有几个词，四选一凑不齐三个
/// 「长得不一样」的干扰项。这时不在现场拼造假单词（那样会教错拼写，而且天生
/// 就长得像），而是从这份真实常用词里挑。备用词排在「词库里的词（包括本局
/// 用过的）」之后才用——你没学过的词一眼就能排除，等于白送分。
///
/// 每一项都带词性和中文意思：挑中文干扰项时直接用它的意思；挑英文干扰项时
/// 也要用它的意思核对「两个选项都对」的情况（比如题目是「价格」，就不能把
/// price 当成干扰项）。
library;

/// 备用词表里的一个词。
class ReserveWord {
  const ReserveWord(this.spelling, this.pos, this.definition);

  /// 英文拼写。
  final String spelling;

  /// 词性，写法与词库一致（n. / v. / adj. / adv. / num.）。
  final String pos;

  /// 最常用的一个中文意思。
  final String definition;
}

/// 备用词表：几百个真实的常用英文单词及其最常用的中文意思。
const List<ReserveWord> kReserveWords = <ReserveWord>[
  // ---- 名词 ----
  ReserveWord('apple', 'n.', '苹果'),
  ReserveWord('banana', 'n.', '香蕉'),
  ReserveWord('orange', 'n.', '橙子'),
  ReserveWord('grape', 'n.', '葡萄'),
  ReserveWord('lemon', 'n.', '柠檬'),
  ReserveWord('peach', 'n.', '桃子'),
  ReserveWord('tomato', 'n.', '西红柿'),
  ReserveWord('potato', 'n.', '土豆'),
  ReserveWord('carrot', 'n.', '胡萝卜'),
  ReserveWord('onion', 'n.', '洋葱'),
  ReserveWord('bread', 'n.', '面包'),
  ReserveWord('butter', 'n.', '黄油'),
  ReserveWord('cheese', 'n.', '奶酪'),
  ReserveWord('cake', 'n.', '蛋糕'),
  ReserveWord('candy', 'n.', '糖果'),
  ReserveWord('cookie', 'n.', '饼干'),
  ReserveWord('coffee', 'n.', '咖啡'),
  ReserveWord('juice', 'n.', '果汁'),
  ReserveWord('milk', 'n.', '牛奶'),
  ReserveWord('honey', 'n.', '蜂蜜'),
  ReserveWord('salt', 'n.', '盐'),
  ReserveWord('sugar', 'n.', '糖'),
  ReserveWord('soup', 'n.', '汤'),
  ReserveWord('rice', 'n.', '米饭'),
  ReserveWord('noodle', 'n.', '面条'),
  ReserveWord('egg', 'n.', '鸡蛋'),
  ReserveWord('meat', 'n.', '肉'),
  ReserveWord('fish', 'n.', '鱼'),
  ReserveWord('water', 'n.', '水'),
  ReserveWord('table', 'n.', '桌子'),
  ReserveWord('chair', 'n.', '椅子'),
  ReserveWord('sofa', 'n.', '沙发'),
  ReserveWord('bed', 'n.', '床'),
  ReserveWord('desk', 'n.', '书桌'),
  ReserveWord('lamp', 'n.', '台灯'),
  ReserveWord('clock', 'n.', '时钟'),
  ReserveWord('mirror', 'n.', '镜子'),
  ReserveWord('window', 'n.', '窗户'),
  ReserveWord('door', 'n.', '门'),
  ReserveWord('floor', 'n.', '地板'),
  ReserveWord('wall', 'n.', '墙'),
  ReserveWord('roof', 'n.', '屋顶'),
  ReserveWord('kitchen', 'n.', '厨房'),
  ReserveWord('garden', 'n.', '花园'),
  ReserveWord('bedroom', 'n.', '卧室'),
  ReserveWord('bathroom', 'n.', '浴室'),
  ReserveWord('house', 'n.', '房子'),
  ReserveWord('village', 'n.', '村庄'),
  ReserveWord('city', 'n.', '城市'),
  ReserveWord('river', 'n.', '河流'),
  ReserveWord('lake', 'n.', '湖泊'),
  ReserveWord('mountain', 'n.', '高山'),
  ReserveWord('forest', 'n.', '森林'),
  ReserveWord('island', 'n.', '岛屿'),
  ReserveWord('ocean', 'n.', '海洋'),
  ReserveWord('desert', 'n.', '沙漠'),
  ReserveWord('valley', 'n.', '山谷'),
  ReserveWord('beach', 'n.', '海滩'),
  ReserveWord('bridge', 'n.', '桥梁'),
  ReserveWord('tower', 'n.', '塔'),
  ReserveWord('castle', 'n.', '城堡'),
  ReserveWord('museum', 'n.', '博物馆'),
  ReserveWord('library', 'n.', '图书馆'),
  ReserveWord('hospital', 'n.', '医院'),
  ReserveWord('bank', 'n.', '银行'),
  ReserveWord('market', 'n.', '市场'),
  ReserveWord('airport', 'n.', '机场'),
  ReserveWord('station', 'n.', '车站'),
  ReserveWord('hotel', 'n.', '酒店'),
  ReserveWord('restaurant', 'n.', '餐馆'),
  ReserveWord('school', 'n.', '学校'),
  ReserveWord('office', 'n.', '办公室'),
  ReserveWord('factory', 'n.', '工厂'),
  ReserveWord('farm', 'n.', '农场'),
  ReserveWord('zoo', 'n.', '动物园'),
  ReserveWord('park', 'n.', '公园'),
  ReserveWord('street', 'n.', '街道'),
  ReserveWord('tree', 'n.', '树'),
  ReserveWord('flower', 'n.', '花朵'),
  ReserveWord('grass', 'n.', '草地'),
  ReserveWord('leaf', 'n.', '树叶'),
  ReserveWord('seed', 'n.', '种子'),
  ReserveWord('stone', 'n.', '石头'),
  ReserveWord('sand', 'n.', '沙子'),
  ReserveWord('snow', 'n.', '雪'),
  ReserveWord('rain', 'n.', '雨'),
  ReserveWord('wind', 'n.', '风'),
  ReserveWord('cloud', 'n.', '云'),
  ReserveWord('storm', 'n.', '暴风雨'),
  ReserveWord('thunder', 'n.', '雷声'),
  ReserveWord('rainbow', 'n.', '彩虹'),
  ReserveWord('sun', 'n.', '太阳'),
  ReserveWord('moon', 'n.', '月亮'),
  ReserveWord('star', 'n.', '星星'),
  ReserveWord('sky', 'n.', '天空'),
  ReserveWord('dog', 'n.', '狗'),
  ReserveWord('cat', 'n.', '猫'),
  ReserveWord('horse', 'n.', '马'),
  ReserveWord('cow', 'n.', '奶牛'),
  ReserveWord('sheep', 'n.', '绵羊'),
  ReserveWord('pig', 'n.', '猪'),
  ReserveWord('rabbit', 'n.', '兔子'),
  ReserveWord('tiger', 'n.', '老虎'),
  ReserveWord('lion', 'n.', '狮子'),
  ReserveWord('monkey', 'n.', '猴子'),
  ReserveWord('elephant', 'n.', '大象'),
  ReserveWord('bear', 'n.', '熊'),
  ReserveWord('wolf', 'n.', '狼'),
  ReserveWord('fox', 'n.', '狐狸'),
  ReserveWord('bird', 'n.', '鸟'),
  ReserveWord('duck', 'n.', '鸭子'),
  ReserveWord('snake', 'n.', '蛇'),
  ReserveWord('frog', 'n.', '青蛙'),
  ReserveWord('bee', 'n.', '蜜蜂'),
  ReserveWord('butterfly', 'n.', '蝴蝶'),
  ReserveWord('spider', 'n.', '蜘蛛'),
  ReserveWord('shirt', 'n.', '衬衫'),
  ReserveWord('skirt', 'n.', '裙子'),
  ReserveWord('jacket', 'n.', '夹克'),
  ReserveWord('coat', 'n.', '外套'),
  ReserveWord('sweater', 'n.', '毛衣'),
  ReserveWord('trousers', 'n.', '裤子'),
  ReserveWord('shoe', 'n.', '鞋'),
  ReserveWord('sock', 'n.', '袜子'),
  ReserveWord('hat', 'n.', '帽子'),
  ReserveWord('glove', 'n.', '手套'),
  ReserveWord('scarf', 'n.', '围巾'),
  ReserveWord('umbrella', 'n.', '雨伞'),
  ReserveWord('wallet', 'n.', '钱包'),
  ReserveWord('key', 'n.', '钥匙'),
  ReserveWord('bag', 'n.', '包'),
  ReserveWord('box', 'n.', '盒子'),
  ReserveWord('bottle', 'n.', '瓶子'),
  ReserveWord('cup', 'n.', '杯子'),
  ReserveWord('plate', 'n.', '盘子'),
  ReserveWord('bowl', 'n.', '碗'),
  ReserveWord('spoon', 'n.', '勺子'),
  ReserveWord('knife', 'n.', '刀'),
  ReserveWord('fork', 'n.', '叉子'),
  ReserveWord('pencil', 'n.', '铅笔'),
  ReserveWord('eraser', 'n.', '橡皮'),
  ReserveWord('ruler', 'n.', '尺子'),
  ReserveWord('notebook', 'n.', '笔记本'),
  ReserveWord('dictionary', 'n.', '词典'),
  ReserveWord('newspaper', 'n.', '报纸'),
  ReserveWord('magazine', 'n.', '杂志'),
  ReserveWord('letter', 'n.', '信件'),
  ReserveWord('envelope', 'n.', '信封'),
  ReserveWord('stamp', 'n.', '邮票'),
  ReserveWord('ticket', 'n.', '票'),
  ReserveWord('map', 'n.', '地图'),
  ReserveWord('camera', 'n.', '相机'),
  ReserveWord('radio', 'n.', '收音机'),
  ReserveWord('computer', 'n.', '电脑'),
  ReserveWord('telephone', 'n.', '电话'),
  ReserveWord('guitar', 'n.', '吉他'),
  ReserveWord('piano', 'n.', '钢琴'),
  ReserveWord('violin', 'n.', '小提琴'),
  ReserveWord('drum', 'n.', '鼓'),
  ReserveWord('ball', 'n.', '球'),
  ReserveWord('toy', 'n.', '玩具'),
  ReserveWord('doctor', 'n.', '医生'),
  ReserveWord('nurse', 'n.', '护士'),
  ReserveWord('teacher', 'n.', '老师'),
  ReserveWord('student', 'n.', '学生'),
  ReserveWord('farmer', 'n.', '农民'),
  ReserveWord('driver', 'n.', '司机'),
  ReserveWord('chef', 'n.', '厨师'),
  ReserveWord('singer', 'n.', '歌手'),
  ReserveWord('painter', 'n.', '画家'),
  ReserveWord('pilot', 'n.', '飞行员'),
  ReserveWord('soldier', 'n.', '士兵'),
  ReserveWord('police', 'n.', '警察'),
  ReserveWord('lawyer', 'n.', '律师'),
  ReserveWord('engineer', 'n.', '工程师'),
  ReserveWord('friend', 'n.', '朋友'),
  ReserveWord('neighbor', 'n.', '邻居'),
  ReserveWord('king', 'n.', '国王'),
  ReserveWord('queen', 'n.', '王后'),
  ReserveWord('prince', 'n.', '王子'),
  ReserveWord('child', 'n.', '孩子'),
  ReserveWord('baby', 'n.', '婴儿'),
  ReserveWord('uncle', 'n.', '叔叔'),
  ReserveWord('aunt', 'n.', '阿姨'),
  ReserveWord('son', 'n.', '儿子'),
  ReserveWord('daughter', 'n.', '女儿'),
  ReserveWord('hand', 'n.', '手'),
  ReserveWord('foot', 'n.', '脚'),
  ReserveWord('finger', 'n.', '手指'),
  ReserveWord('nose', 'n.', '鼻子'),
  ReserveWord('mouth', 'n.', '嘴巴'),
  ReserveWord('tooth', 'n.', '牙齿'),
  ReserveWord('ear', 'n.', '耳朵'),
  ReserveWord('eye', 'n.', '眼睛'),
  ReserveWord('hair', 'n.', '头发'),
  ReserveWord('heart', 'n.', '心脏'),
  ReserveWord('face', 'n.', '脸'),
  ReserveWord('shoulder', 'n.', '肩膀'),
  ReserveWord('knee', 'n.', '膝盖'),
  ReserveWord('spring', 'n.', '春天'),
  ReserveWord('summer', 'n.', '夏天'),
  ReserveWord('autumn', 'n.', '秋天'),
  ReserveWord('winter', 'n.', '冬天'),
  ReserveWord('morning', 'n.', '早晨'),
  ReserveWord('evening', 'n.', '傍晚'),
  ReserveWord('night', 'n.', '夜晚'),
  ReserveWord('weekend', 'n.', '周末'),
  ReserveWord('holiday', 'n.', '假日'),
  ReserveWord('birthday', 'n.', '生日'),
  ReserveWord('music', 'n.', '音乐'),
  ReserveWord('movie', 'n.', '电影'),
  ReserveWord('song', 'n.', '歌曲'),
  ReserveWord('story', 'n.', '故事'),
  ReserveWord('game', 'n.', '游戏'),
  ReserveWord('sport', 'n.', '体育运动'),
  ReserveWord('football', 'n.', '足球'),
  ReserveWord('color', 'n.', '颜色'),
  ReserveWord('shape', 'n.', '形状'),
  ReserveWord('price', 'n.', '价格'),
  ReserveWord('money', 'n.', '钱'),
  ReserveWord('gift', 'n.', '礼物'),
  ReserveWord('dream', 'n.', '梦'),
  ReserveWord('idea', 'n.', '主意'),
  ReserveWord('question', 'n.', '问题'),
  ReserveWord('answer', 'n.', '答案'),
  ReserveWord('lesson', 'n.', '课'),
  ReserveWord('homework', 'n.', '家庭作业'),
  ReserveWord('journey', 'n.', '旅程'),
  ReserveWord('picture', 'n.', '图画'),
  ReserveWord('voice', 'n.', '嗓音'),
  ReserveWord('circle', 'n.', '圆圈'),
  ReserveWord('square', 'n.', '正方形'),
  ReserveWord('triangle', 'n.', '三角形'),
  ReserveWord('kettle', 'n.', '水壶'),
  ReserveWord('blanket', 'n.', '毯子'),
  ReserveWord('pillow', 'n.', '枕头'),
  ReserveWord('towel', 'n.', '毛巾'),
  ReserveWord('soap', 'n.', '肥皂'),
  ReserveWord('candle', 'n.', '蜡烛'),
  ReserveWord('basket', 'n.', '篮子'),
  ReserveWord('ladder', 'n.', '梯子'),
  ReserveWord('hammer', 'n.', '锤子'),
  ReserveWord('rope', 'n.', '绳子'),
  ReserveWord('wheel', 'n.', '轮子'),
  ReserveWord('engine', 'n.', '发动机'),
  ReserveWord('truck', 'n.', '卡车'),
  ReserveWord('bicycle', 'n.', '自行车'),
  ReserveWord('boat', 'n.', '小船'),
  ReserveWord('ship', 'n.', '轮船'),
  ReserveWord('train', 'n.', '火车'),
  ReserveWord('plane', 'n.', '飞机'),
  ReserveWord('bus', 'n.', '公共汽车'),
  // ---- 动词 ----
  ReserveWord('run', 'v.', '跑'),
  ReserveWord('walk', 'v.', '走路'),
  ReserveWord('jump', 'v.', '跳'),
  ReserveWord('swim', 'v.', '游泳'),
  ReserveWord('fly', 'v.', '飞'),
  ReserveWord('climb', 'v.', '攀登'),
  ReserveWord('dance', 'v.', '跳舞'),
  ReserveWord('sing', 'v.', '唱歌'),
  ReserveWord('laugh', 'v.', '大笑'),
  ReserveWord('smile', 'v.', '微笑'),
  ReserveWord('cry', 'v.', '哭'),
  ReserveWord('sleep', 'v.', '睡觉'),
  ReserveWord('wake', 'v.', '醒来'),
  ReserveWord('eat', 'v.', '吃'),
  ReserveWord('drink', 'v.', '喝'),
  ReserveWord('cook', 'v.', '烹饪'),
  ReserveWord('wash', 'v.', '洗'),
  ReserveWord('open', 'v.', '打开'),
  ReserveWord('close', 'v.', '关闭'),
  ReserveWord('push', 'v.', '推'),
  ReserveWord('pull', 'v.', '拉'),
  ReserveWord('throw', 'v.', '扔'),
  ReserveWord('catch', 'v.', '接住'),
  ReserveWord('carry', 'v.', '搬运'),
  ReserveWord('lift', 'v.', '举起'),
  ReserveWord('build', 'v.', '建造'),
  ReserveWord('break', 'v.', '打破'),
  ReserveWord('fix', 'v.', '修理'),
  ReserveWord('draw', 'v.', '画画'),
  ReserveWord('write', 'v.', '写'),
  ReserveWord('read', 'v.', '阅读'),
  ReserveWord('listen', 'v.', '听'),
  ReserveWord('speak', 'v.', '说话'),
  ReserveWord('shout', 'v.', '喊叫'),
  ReserveWord('whisper', 'v.', '低语'),
  ReserveWord('ask', 'v.', '询问'),
  ReserveWord('teach', 'v.', '教'),
  ReserveWord('learn', 'v.', '学习'),
  ReserveWord('think', 'v.', '思考'),
  ReserveWord('remember', 'v.', '记得'),
  ReserveWord('forget', 'v.', '忘记'),
  ReserveWord('choose', 'v.', '选择'),
  ReserveWord('decide', 'v.', '决定'),
  ReserveWord('begin', 'v.', '开始'),
  ReserveWord('finish', 'v.', '完成'),
  ReserveWord('stop', 'v.', '停止'),
  ReserveWord('wait', 'v.', '等待'),
  ReserveWord('arrive', 'v.', '到达'),
  ReserveWord('leave', 'v.', '离开'),
  ReserveWord('return', 'v.', '返回'),
  ReserveWord('visit', 'v.', '拜访'),
  ReserveWord('travel', 'v.', '旅行'),
  ReserveWord('buy', 'v.', '买'),
  ReserveWord('sell', 'v.', '卖'),
  ReserveWord('pay', 'v.', '付款'),
  ReserveWord('borrow', 'v.', '借入'),
  ReserveWord('lend', 'v.', '借出'),
  ReserveWord('send', 'v.', '发送'),
  ReserveWord('receive', 'v.', '收到'),
  ReserveWord('invite', 'v.', '邀请'),
  ReserveWord('agree', 'v.', '同意'),
  ReserveWord('refuse', 'v.', '拒绝'),
  ReserveWord('help', 'v.', '帮助'),
  ReserveWord('hurry', 'v.', '赶紧'),
  ReserveWord('grow', 'v.', '生长'),
  ReserveWord('plant', 'v.', '种植'),
  ReserveWord('hide', 'v.', '躲藏'),
  ReserveWord('search', 'v.', '搜寻'),
  ReserveWord('explore', 'v.', '探索'),
  ReserveWord('collect', 'v.', '收集'),
  ReserveWord('count', 'v.', '数数'),
  ReserveWord('measure', 'v.', '测量'),
  ReserveWord('repeat', 'v.', '重复'),
  ReserveWord('practice', 'v.', '练习'),
  ReserveWord('win', 'v.', '赢'),
  ReserveWord('lose', 'v.', '输掉'),
  ReserveWord('hope', 'v.', '希望'),
  ReserveWord('worry', 'v.', '担心'),
  ReserveWord('believe', 'v.', '相信'),
  ReserveWord('promise', 'v.', '承诺'),
  ReserveWord('explain', 'v.', '解释'),
  ReserveWord('describe', 'v.', '描述'),
  ReserveWord('imagine', 'v.', '想象'),
  ReserveWord('protect', 'v.', '保护'),
  ReserveWord('celebrate', 'v.', '庆祝'),
  ReserveWord('knock', 'v.', '敲门'),
  // ---- 形容词 ----
  ReserveWord('happy', 'adj.', '快乐的'),
  ReserveWord('sad', 'adj.', '伤心的'),
  ReserveWord('angry', 'adj.', '生气的'),
  ReserveWord('tired', 'adj.', '疲倦的'),
  ReserveWord('hungry', 'adj.', '饥饿的'),
  ReserveWord('thirsty', 'adj.', '口渴的'),
  ReserveWord('busy', 'adj.', '忙碌的'),
  ReserveWord('lazy', 'adj.', '懒惰的'),
  ReserveWord('brave', 'adj.', '勇敢的'),
  ReserveWord('shy', 'adj.', '害羞的'),
  ReserveWord('kind', 'adj.', '善良的'),
  ReserveWord('polite', 'adj.', '礼貌的'),
  ReserveWord('honest', 'adj.', '诚实的'),
  ReserveWord('clever', 'adj.', '聪明的'),
  ReserveWord('funny', 'adj.', '滑稽的'),
  ReserveWord('quiet', 'adj.', '安静的'),
  ReserveWord('noisy', 'adj.', '吵闹的'),
  ReserveWord('clean', 'adj.', '干净的'),
  ReserveWord('dirty', 'adj.', '肮脏的'),
  ReserveWord('hot', 'adj.', '炎热的'),
  ReserveWord('cold', 'adj.', '寒冷的'),
  ReserveWord('warm', 'adj.', '温暖的'),
  ReserveWord('cool', 'adj.', '凉爽的'),
  ReserveWord('wet', 'adj.', '潮湿的'),
  ReserveWord('dry', 'adj.', '干燥的'),
  ReserveWord('heavy', 'adj.', '沉重的'),
  ReserveWord('big', 'adj.', '巨大的'),
  ReserveWord('small', 'adj.', '小的'),
  ReserveWord('tall', 'adj.', '高的'),
  ReserveWord('short', 'adj.', '短的'),
  ReserveWord('long', 'adj.', '长的'),
  ReserveWord('wide', 'adj.', '宽阔的'),
  ReserveWord('narrow', 'adj.', '狭窄的'),
  ReserveWord('thick', 'adj.', '厚的'),
  ReserveWord('thin', 'adj.', '薄的'),
  ReserveWord('deep', 'adj.', '深的'),
  ReserveWord('fast', 'adj.', '迅速的'),
  ReserveWord('slow', 'adj.', '缓慢的'),
  ReserveWord('early', 'adj.', '早的'),
  ReserveWord('late', 'adj.', '迟的'),
  ReserveWord('new', 'adj.', '新的'),
  ReserveWord('old', 'adj.', '旧的'),
  ReserveWord('young', 'adj.', '年轻的'),
  ReserveWord('rich', 'adj.', '富有的'),
  ReserveWord('poor', 'adj.', '贫穷的'),
  ReserveWord('cheap', 'adj.', '便宜的'),
  ReserveWord('expensive', 'adj.', '昂贵的'),
  ReserveWord('beautiful', 'adj.', '美丽的'),
  ReserveWord('ugly', 'adj.', '丑陋的'),
  ReserveWord('strong', 'adj.', '强壮的'),
  ReserveWord('weak', 'adj.', '虚弱的'),
  ReserveWord('sweet', 'adj.', '甜的'),
  ReserveWord('sour', 'adj.', '酸的'),
  ReserveWord('bitter', 'adj.', '苦的'),
  ReserveWord('salty', 'adj.', '咸的'),
  ReserveWord('soft', 'adj.', '柔软的'),
  ReserveWord('hard', 'adj.', '坚硬的'),
  ReserveWord('bright', 'adj.', '明亮的'),
  ReserveWord('dark', 'adj.', '黑暗的'),
  ReserveWord('empty', 'adj.', '空的'),
  ReserveWord('full', 'adj.', '满的'),
  ReserveWord('easy', 'adj.', '容易的'),
  ReserveWord('difficult', 'adj.', '困难的'),
  ReserveWord('famous', 'adj.', '著名的'),
  ReserveWord('dangerous', 'adj.', '危险的'),
  ReserveWord('safe', 'adj.', '安全的'),
  ReserveWord('useful', 'adj.', '有用的'),
  ReserveWord('careful', 'adj.', '小心的'),
  ReserveWord('correct', 'adj.', '正确的'),
  ReserveWord('simple', 'adj.', '简单的'),
  ReserveWord('strange', 'adj.', '奇怪的'),
  ReserveWord('modern', 'adj.', '现代的'),
  ReserveWord('ancient', 'adj.', '古代的'),
  ReserveWord('round', 'adj.', '圆形的'),
  ReserveWord('purple', 'adj.', '紫色的'),
  ReserveWord('yellow', 'adj.', '黄色的'),
  ReserveWord('green', 'adj.', '绿色的'),
  // ---- 副词 ----
  ReserveWord('quickly', 'adv.', '快速地'),
  ReserveWord('slowly', 'adv.', '慢慢地'),
  ReserveWord('quietly', 'adv.', '悄悄地'),
  ReserveWord('loudly', 'adv.', '大声地'),
  ReserveWord('carefully', 'adv.', '仔细地'),
  ReserveWord('happily', 'adv.', '高兴地'),
  ReserveWord('often', 'adv.', '经常'),
  ReserveWord('always', 'adv.', '总是'),
  ReserveWord('never', 'adv.', '从不'),
  ReserveWord('sometimes', 'adv.', '有时'),
  ReserveWord('usually', 'adv.', '通常'),
  ReserveWord('together', 'adv.', '一起'),
  ReserveWord('again', 'adv.', '再一次'),
  ReserveWord('almost', 'adv.', '几乎'),
  ReserveWord('suddenly', 'adv.', '突然'),
  // ---- 数词 ----
  ReserveWord('seven', 'num.', '七'),
  ReserveWord('eleven', 'num.', '十一'),
  ReserveWord('twelve', 'num.', '十二'),
  ReserveWord('twenty', 'num.', '二十'),
  ReserveWord('thirty', 'num.', '三十'),
  ReserveWord('hundred', 'num.', '百'),
  ReserveWord('thousand', 'num.', '千'),
  ReserveWord('million', 'num.', '百万'),
];

/// 常见同音词：读音相同、拼写不同。
///
/// 听音辨义的「听音选单词」题只能靠耳朵分辨，如果干扰项和答案读音一样
/// （right / write），听起来两个都对，所以同一组里的词不能互相当干扰项。
/// 看义选词是看中文选英文，不受影响。
const List<List<String>> kHomophoneGroups = <List<String>>[
  <String>['right', 'write', 'rite'],
  <String>['there', 'their'],
  <String>['to', 'too', 'two'],
  <String>['hear', 'here'],
  <String>['know', 'no'],
  <String>['knew', 'new'],
  <String>['knight', 'night'],
  <String>['knot', 'not'],
  <String>['see', 'sea'],
  <String>['meet', 'meat'],
  <String>['week', 'weak'],
  <String>['sun', 'son'],
  <String>['one', 'won'],
  <String>['eight', 'ate'],
  <String>['for', 'four', 'fore'],
  <String>['by', 'buy', 'bye'],
  <String>['hour', 'our'],
  <String>['flower', 'flour'],
  <String>['piece', 'peace'],
  <String>['whole', 'hole'],
  <String>['wait', 'weight'],
  <String>['weather', 'whether'],
  <String>['road', 'rode'],
  <String>['sail', 'sale'],
  <String>['tail', 'tale'],
  <String>['mail', 'male'],
  <String>['pair', 'pear', 'pare'],
  <String>['plain', 'plane'],
  <String>['rain', 'reign', 'rein'],
  <String>['read', 'reed'],
  <String>['red', 'read'],
  <String>['blue', 'blew'],
  <String>['break', 'brake'],
  <String>['steal', 'steel'],
  <String>['stair', 'stare'],
  <String>['principal', 'principle'],
  <String>['bare', 'bear'],
  <String>['dear', 'deer'],
  <String>['fair', 'fare'],
  <String>['hair', 'hare'],
  <String>['heal', 'heel'],
  <String>['hi', 'high'],
  <String>['made', 'maid'],
  <String>['pain', 'pane'],
  <String>['peak', 'peek'],
  <String>['pole', 'poll'],
  <String>['pray', 'prey'],
  <String>['root', 'route'],
  <String>['scene', 'seen'],
  <String>['sole', 'soul'],
  <String>['some', 'sum'],
  <String>['stationary', 'stationery'],
  <String>['sweet', 'suite'],
  <String>['tea', 'tee'],
  <String>['threw', 'through'],
  <String>['toe', 'tow'],
  <String>['wear', 'where'],
  <String>['which', 'witch'],
  <String>['wood', 'would'],
  <String>['allowed', 'aloud'],
  <String>['board', 'bored'],
  <String>['cell', 'sell'],
  <String>['cent', 'scent', 'sent'],
  <String>['cereal', 'serial'],
  <String>['check', 'cheque'],
  <String>['die', 'dye'],
  <String>['flea', 'flee'],
  <String>['grate', 'great'],
  <String>['groan', 'grown'],
  <String>['guessed', 'guest'],
  <String>['hall', 'haul'],
  <String>['higher', 'hire'],
  <String>['in', 'inn'],
  <String>['lead', 'led'],
  <String>['loan', 'lone'],
  <String>['missed', 'mist'],
  <String>['morning', 'mourning'],
  <String>['need', 'knead'],
  <String>['none', 'nun'],
  <String>['oar', 'or', 'ore'],
  <String>['passed', 'past'],
  <String>['patience', 'patients'],
  <String>['presence', 'presents'],
  <String>['rap', 'wrap'],
  <String>['ring', 'wring'],
  <String>['role', 'roll'],
  <String>['rose', 'rows'],
  <String>['sew', 'so', 'sow'],
  <String>['sight', 'site', 'cite'],
  <String>['stake', 'steak'],
  <String>['tide', 'tied'],
  <String>['vain', 'vein', 'vane'],
  <String>['waist', 'waste'],
  <String>['wail', 'whale'],
  <String>['war', 'wore'],
  <String>['way', 'weigh'],
  <String>['whine', 'wine'],
  <String>['yoke', 'yolk'],
  <String>['aisle', 'isle'],
  <String>['bread', 'bred'],
  <String>['colonel', 'kernel'],
  <String>['ball', 'bawl'],
  <String>['band', 'banned'],
  <String>['course', 'coarse'],
  <String>['chews', 'choose'],
  <String>['fir', 'fur'],
  <String>['genes', 'jeans'],
  <String>['mind', 'mined'],
  <String>['plum', 'plumb'],
  <String>['side', 'sighed'],
  <String>['whose', "who's"],
  <String>['its', "it's"],
  <String>['your', "you're"],
];
