// 引入 dart:io 的 File，用于读取 my_english/pubspec.yaml。
import 'dart:io';
// 引入路径拼接，让脚本在任何工作目录下都能定位 pubspec.yaml。
import 'package:path/path.dart' as p;

// tools/sync_app_info.dart
//
// 从 my_english/pubspec.yaml 同步生成 lib/common/app_info.dart，
// 让运行时的版本号 / Build 号 / 展示名跟随 pubspec 单一数据源。
//
// 使用方式（修改 pubspec.yaml 后重新同步）：
//   dart run tools/sync_app_info.dart
//
// 为什么要这个脚本？
// Flutter 运行时没有官方 API 直接读 pubspec.yaml 内容（dart:io 在 release
// 包里读不到项目内的 pubspec.yaml）。如果用 package_info_plus 插件间接读
// 原生 manifest，又会引入 pub 依赖、在网络受限环境下不可用。
// 这里采用「构建期代码生成」路线：pubspec.yaml 是单一数据源，本脚本把
// version / buildNumber / package name 提取出来，生成 Dart 常量文件
// 让运行时直接读取。生成的 app_info.dart 需要提交到版本控制。
//
// 注意：本脚本必须在 my_english/ 目录下运行（脚本内会向上找到 pubspec.yaml）。

/// 同步生成 lib/common/app_info.dart。
Future<void> main() async {
  // 1. 定位 pubspec.yaml。
  // 脚本位于 my_english/tools/sync_app_info.dart，
  // pubspec.yaml 位于 my_english/pubspec.yaml（脚本上一层）。
  // Platform.script 在 `dart run` 时给出当前脚本的绝对路径。
  final scriptFile = File(Platform.script.toFilePath());
  // 脚本所在目录。
  final scriptDir = scriptFile.parent;
  // my_english 根目录（脚本上一层）。
  final projectRoot = scriptDir.parent;
  final pubspecFile = File(p.join(projectRoot.path, 'pubspec.yaml'));

  // 2. 兜底：如果上面定位失败，尝试当前工作目录。
  final resolvedPubspec = pubspecFile.existsSync()
      ? pubspecFile
      : File(p.join(Directory.current.path, 'pubspec.yaml'));

  if (!resolvedPubspec.existsSync()) {
    // pubspec.yaml 找不到就终止，避免生成空内容覆盖已有常量。
    stderr.writeln('未找到 pubspec.yaml：${resolvedPubspec.path}');
    exit(1);
  }

  // 3. 解析 pubspec.yaml 中的 name / version。
  // 简单按行扫描（不引入 yaml 包），匹配 `name:` 与 `version:`。
  // pubspec.yaml 是受控文件，行格式稳定，正则足够。
  final lines = await resolvedPubspec.readAsLines();
  String? packageName;
  String? versionRaw;
  String? buildNumberRaw;
  // name: my_english / version: 0.22.1+5 形式的简单解析。
  final nameRegex = RegExp(r'^\s*name\s*:\s*([\w_]+)\s*$');
  final versionRegex = RegExp(r'^\s*version\s*:\s*([0-9]+(?:\.[0-9]+){0,2})(?:\+([0-9]+))?\s*$');
  for (final line in lines) {
    // 跳过注释行（以 # 开头）。
    if (line.trimLeft().startsWith('#')) continue;
    // 抓包名。
    final nameMatch = nameRegex.firstMatch(line);
    if (nameMatch != null && packageName == null) {
      packageName = nameMatch.group(1);
    }
    // 抓版本号 + 构建号（同一个匹配里 group(1) 是 X.Y.Z，group(2) 是 +N）。
    final versionMatch = versionRegex.firstMatch(line);
    if (versionMatch != null && versionRaw == null) {
      versionRaw = versionMatch.group(1);
      buildNumberRaw = versionMatch.group(2);
    }
  }

  if (packageName == null || versionRaw == null) {
    // 关键字段缺失则报错，避免生成不完整文件。
    stderr.writeln('pubspec.yaml 缺少 name 或 version 字段。');
    stderr.writeln('  name=$packageName');
    stderr.writeln('  version=$versionRaw');
    exit(1);
  }

  // 4. 拆分 version 与 buildNumber（pubspec 格式 `version: X.Y.Z+N`）。
  // 例如 0.22.2+6 → version=0.22.2，buildNumber=6。
  // buildNumber 直接用正则 group(2)，未设置时为 '0'。
  final version = versionRaw;
  final buildNumber = buildNumberRaw ?? '0';

  // 5. 展示名约定：包名转 PascalCase。
  // my_english → MyEnglish；这种规则覆盖大多数情况。
  String displayName(String pkg) {
    if (pkg.isEmpty) return pkg;
    // 按 _ 切分，每段首字母大写后拼接。
    final parts = pkg.split('_').where((s) => s.isNotEmpty);
    return parts
        .map((s) => s[0].toUpperCase() + s.substring(1).toLowerCase())
        .join();
  }

  // 6. 生成 lib/common/app_info.dart 内容。
  // 头部注释明确说明「本文件由 tools/sync_app_info.dart 生成，请勿手改」。
  final generatedAt = DateTime.now().toIso8601String();
  final content = '''// GENERATED BY tools/sync_app_info.dart - DO NOT EDIT BY HAND.
// 在 pubspec.yaml 中修改 name/version 后，跑下面命令重新生成本文件：
//   dart run tools/sync_app_info.dart
// 生成时间：$generatedAt
// 数据来源：${resolvedPubspec.path}

/// 应用元信息（由 pubspec.yaml 同步生成，单一数据源在 pubspec.yaml）。
class AppInfo {
  /// 包名（pubspec.yaml `name` 字段），与 Dart import 路径一致。
  static const String packageName = '$packageName';

  /// 展示名（系统 launcher / Drawer 头部 / MaterialApp.title 用）。
  ///
  /// 当前约定：包名转 PascalCase。如需自定义展示名（如含空格或特殊字符），
  /// 在 pubspec.yaml 添加 `display_name: ...` 字段并扩展本脚本。
  static const String displayName = '${displayName(packageName)}';

  /// 用户可见版本号（pubspec.yaml `version` 字段的 `X.Y.Z` 段）。
  static const String version = '$version';

  /// 构建号（pubspec.yaml `version` 字段的 `+N` 段，0 表示未设置）。
  static const String buildNumber = '$buildNumber';

  /// 完整的 `version+buildNumber` 字符串，便于单一展示。
  static const String fullVersion = '$version+\$buildNumber';
}
''';

  // 7. 写入 lib/common/app_info.dart。
  final outFile = File(p.join(projectRoot.path, 'lib', 'common', 'app_info.dart'));
  // 兜底：如果脚本所在目录定位失败，写到当前工作目录。
  final resolvedOut = outFile.parent.path.contains('lib')
      ? outFile
      : File(p.join(Directory.current.path, 'lib', 'common', 'app_info.dart'));
  // 自动建目录（首次生成时 common/ 已存在，但保险起见 mkdir -p）。
  resolvedOut.parent.createSync(recursive: true);
  await resolvedOut.writeAsString(content);

  // 8. 输出同步结果。
  stdout.writeln('已同步：${resolvedOut.path}');
  stdout.writeln('  packageName = $packageName');
  stdout.writeln('  displayName = ${displayName(packageName)}');
  stdout.writeln('  version     = $version');
  stdout.writeln('  buildNumber = $buildNumber');
}